Nanaweb\WordPressBundle\Entity\Comment:
    type: entity
    table: wp_comments
    indexes:
        comment_post_ID:
            columns:
                - comment_post_ID
        comment_approved_date_gmt:
            columns:
                - comment_approved
                - comment_date_gmt
        comment_date_gmt:
            columns:
                - comment_date_gmt
        comment_parent:
            columns:
                - comment_parent
    id:
        id:
            type: bigint
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: comment_ID
            generator:
                strategy: IDENTITY
    fields:
        postId:
            type: bigint
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: comment_post_ID
        author:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: comment_author
        authorEmail:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: comment_author_email
        authorUrl:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            default: ''
            column: comment_author_url
        authorIp:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: comment_author_IP
        created:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: comment_date
        createdGmt:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: comment_date_gmt
        content:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: comment_content
        karma:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: comment_karma
        approved:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: '1'
            column: comment_approved
        agent:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
            column: comment_agent
        type:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
            column: comment_type
        parentId:
            type: bigint
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: comment_parent
        userId:
            type: bigint
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: user_id
    lifecycleCallbacks: {  }
    manyToOne:
        parent:
            targetEntity: Comment
            joinColumn:
                name: comment_parent
                referencedColumnName: comment_ID
        post:
            targetEntity: Post
            joinColumn:
                name: comment_post_ID
                referencedColumnName: ID
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: id