Nanaweb\WordPressBundle\Entity\Link:
    type: entity
    table: wp_links
    indexes:
        link_visible:
            columns:
                - link_visible
    id:
        id:
            type: bigint
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: link_id
            generator:
                strategy: IDENTITY
    fields:
        url:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
            column: link_url
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
            column: link_name
        image:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
            column: link_image
        target:
            type: string
            nullable: false
            length: 25
            fixed: false
            comment: ''
            default: ''
            column: link_target
        description:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
            column: link_description
        visible:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: Y
            column: link_visible
        owner:
            type: bigint
            nullable: false
            unsigned: true
            comment: ''
            default: '1'
            column: link_owner
        rating:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: link_rating
        updated:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: link_updated
        rel:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
            column: link_rel
        note:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: link_notes
        rss:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
            column: link_rss
    lifecycleCallbacks: {  }
