Nanaweb\WordPressBundle\Entity\Option:
    type: entity
    table: wp_options
    uniqueConstraints:
        option_name:
            columns:
                - option_name
    id:
        id:
            type: bigint
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: option_id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: ''
            default: ''
            column: option_name
        value:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: option_value
        autoload:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: yes
    lifecycleCallbacks: {  }
