Nanaweb\WordPressBundle\Entity\Post:
    type: entity
    table: wp_posts
    indexes:
        post_name:
            columns:
                - post_name
        type_status_date:
            columns:
                - post_type
                - post_status
                - post_date
                - ID
        post_parent:
            columns:
                - post_parent
        post_author:
            columns:
                - post_author
    id:
        id:
            type: bigint
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: bigint
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: post_author
        published:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: post_date
        publishedGmt:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: post_date_gmt
        content:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: post_content
        title:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: post_title
        excerpt:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: post_excerpt
        status:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: publish
            column: post_status
        commentStatus:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: open
            column: comment_status
        pingStatus:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: open
            column: ping_status
        password:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
            column: post_password
        slug:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            default: ''
            column: post_name
        toPing:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: to_ping
        pinged:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        modified:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: post_modified
        modifiedGmt:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: post_modified_gmt
        contentFiltered:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: post_content_filtered
        parentId:
            type: bigint
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: post_parent
        guid:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        menuOrder:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: menu_order
        type:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: post
            column: post_type
        mimeType:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: post_mime_type
        commentCount:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: comment_count
    lifecycleCallbacks: {  }
    manyToOne:
        author:
            targetEntity: User
            joinColumn:
                name: post_author
                referencedColumnName: id
        parentPost:
            targetEntity: Post
            joinColumn:
                name: post_parent
                referencedColumnName: ID
    oneToMany:
        metas:
            targetEntity: PostMeta
            mappedBy: post
        comments:
            targetEntity: Comment
            mappedBy: post
        childrenPosts:
            targetEntity: Post
            mappedBy: parentPost