Nanaweb\WordPressBundle\Entity\PostMeta:
    type: entity
    table: wp_postmeta
    indexes:
        post_id:
            columns:
                - post_id
        meta_key:
            columns:
                - meta_key
    id:
        id:
            type: bigint
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: meta_id
            generator:
                strategy: IDENTITY
    fields:
        postId:
            type: bigint
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: post_id
        key:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: meta_key
        value:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: meta_value
    lifecycleCallbacks: {  }
    manyToOne:
        post:
            targetEntity: Post
            joinColumn:
                name: post_id
                referencedColumnName: ID