Nanaweb\WordPressBundle\Entity\User:
    type: entity
    table: wp_users
    indexes:
        user_login_key:
            columns:
                - user_login
        user_nicename:
            columns:
                - user_nicename
    id:
        id:
            type: bigint
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
            default: ''
            column: user_login
        password:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: ''
            default: ''
            column: user_pass
        nicename:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: user_nicename
        email:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: user_email
        url:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: user_url
        registered:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: user_registered
        activationKey:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
            default: ''
            column: user_activation_key
        status:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: user_status
        displayName:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
            default: ''
            column: display_name
    lifecycleCallbacks: {  }
