Nanaweb\WordPressBundle\Entity\WpCommentmeta:
    type: entity
    table: wp_commentmeta
    indexes:
        comment_id:
            columns:
                - comment_id
        meta_key:
            columns:
                - meta_key
    id:
        metaId:
            type: bigint
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: meta_id
            generator:
                strategy: IDENTITY
    fields:
        commentId:
            type: bigint
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: comment_id
        metaKey:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: meta_key
        metaValue:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: meta_value
    lifecycleCallbacks: {  }
