Nanaweb\WordPressBundle\Entity\WpUsermeta:
    type: entity
    table: wp_usermeta
    indexes:
        user_id:
            columns:
                - user_id
        meta_key:
            columns:
                - meta_key
    id:
        umetaId:
            type: bigint
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: umeta_id
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: bigint
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: user_id
        metaKey:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: meta_key
        metaValue:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: meta_value
    lifecycleCallbacks: {  }
