parameters:
#    nanaweb_word_press.example.class: Nanaweb\WordPressBundle\Example

services:
#    nanaweb_word_press.example:
#        class: %nanaweb_word_press.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
